name: docker hello world!
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v1

      - name: login azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: demo38.azurecr.io/hello-python:latest
      
     
    
